apiVersion: v1
kind: Secret
metadata:
  name: weaviate-secret
type: Opaque
data:
  AUTHENTICATION_APIKEY_ALLOWED_KEYS: NE1TUmZGZEZLWGtWdG4wb0Z6NWNBeUtJUTgzc2xRcDJJZThx
  AUTHENTICATION_APIKEY_USERS: ZGFuaWVsLnRAYWFpLWxhYnMuY29t
  HUGGINGFACE_APIKEY: aGZfQU9BZnp6S3B6aVhPc1FlV0lDZGxMY25hWFVkbFBURFZWdg==
