apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: d2VhdmlhdGV2ZWN0b3JkYg==
  azurestorageaccountkey: UHJweDBjcXBYU1FncWI4V21XU05EbmFBY0xSL2FVYldRdTV4T1NseC8za3diNXhLWEFPT3JCaEVORUNWZ1M3dHdVenpKZ1V1OXBvVStBU3RaeEY3NlE9PQ==
